# Preprocessing dataset 1

Before we start with the models, we first need to preprocess the dataset torgua for tech student profile prediction.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

We first need to load the dataset in here:

In [2]:
data = pd.read_csv('Datasets/Synthetic_dataset_1/dataset-tortuga.csv')
data

,Unnamed: 0,NAME,USER_ID,HOURS_DATASCIENCE,HOURS_BACKEND,HOURS_FRONTEND,NUM_COURSES_BEGINNER_DATASCIENCE,NUM_COURSES_BEGINNER_BACKEND,NUM_COURSES_BEGINNER_FRONTEND,NUM_COURSES_ADVANCED_DATASCIENCE,NUM_COURSES_ADVANCED_BACKEND,NUM_COURSES_ADVANCED_FRONTEND,AVG_SCORE_DATASCIENCE,AVG_SCORE_BACKEND,AVG_SCORE_FRONTEND,PROFILE
0,28,Stormy Muto,58283940,7.0,39.0,29.0,2.0,4.0,0.0,2.0,5.0,0.0,84.0,74.0,NaN,beginner_front_end
1,81,Carlos Ferro,1357218,32.0,0.0,44.0,2.0,0.0,0.0,0.0,5.0,0.0,67.0,45.0,NaN,beginner_front_end
2,89,Robby Constantini,63212105,45.0,0.0,59.0,0.0,5.0,4.0,0.0,4.0,1.0,NaN,54.0,47.0,advanced_front_end
3,138,Paul Mckenny,23239851,36.0,19.0,28.0,0.0,5.0,7.0,0.0,5.0,3.0,NaN,71.0,89.0,beginner_data_science
4,143,Jean Webb,72234478,61.0,78.0,38.0,6.0,11.0,0.0,4.0,3.0,0.0,66.0,85.0,NaN,advanced_front_end
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,20495,Rose Jurado,66754730,0.0,44.0,42.0,8.0,4.0,7.0,3.0,3.0,3.0,74.0,73.0,93.0,advanced_backend
19996,20496,Johnny Jones,6874888,0.0,85.0,63.0,3.0,5.0,0.0,4.0,7.0,3.0,50.0,83.0,94.0,advanced_front_end
19997,20497,Lawrence Givens,83752787,32.0,50.0,22.0,0.0,4.0,0.0,6.0,2.0,3.0,61.0,81.0,75.0,advanced_backend
19998,20498,Betty Diclaudio,45806698,0.0,96.0,69.0,3.0,3.0,3.0,5.0,7.0,4.0,64.0,68.0,68.0,advanced_front_end
19999,20499,Connie Harper,67068866,51.0,24.0,36.0,4.0,2.0,7.0,0.0,0.0,2.0,63.0,61.0,87.0,advanced_data_science

Features (X)

Unnamed: 0 - Useless column

NAME - Name of the student

USERID - ID for each student

HOURSDATASCIENCE - Numbers of hours studied data science courses

HOURSBACKEND - Numbers of hours studied web (Back-End)

HOURSFRONTEND - Numbers of hours studied web (Front-End)

NUMCOURSESBEGINNERDATASCIENCE - Numbers of beginner courses of Data Science completed by the student

NUMCOURSESBEGINNERBACKEND - Numbers of beginner courses of Web (Back-End) completed by the student

NUMCOURSESBEGINNERFRONTEND - Numbers of beginner courses of Web (Front-End) completed by the student

NUMCOURSESADVANCEDDATASCIENCE -Numbers of advanced courses of Data Science completed by the student

NUMCOURSESADVANCEDBACKEND - Numbers of advanced courses of Web (Back-End) completed by the student

NUMCOURSESADVANCEDFRONTEND - Numbers of advanced courses of Web (Front-End) completed by the student

AVGSCOREDATASCIENCE - Average score in Data Science completed by the student

AVGSCOREBACKEND - Average score in Web (Back-End) completed by the student

AVGSCOREFRONTEND - Average score in Web (Front-End) completed by the student

In [3]:
print('The amount of missing values: \n'+str(data.isnull().sum().sort_values(ascending=False)))

The amount of missing values:
AVG_SCORE_DATASCIENCE               220
AVG_SCORE_FRONTEND                  168
AVG_SCORE_BACKEND                    84
HOURS_BACKEND                        53
NUM_COURSES_BEGINNER_FRONTEND        39
NUM_COURSES_ADVANCED_FRONTEND        37
NUM_COURSES_BEGINNER_DATASCIENCE     26
NUM_COURSES_BEGINNER_BACKEND         18
HOURS_FRONTEND                       16
HOURS_DATASCIENCE                    14
NUM_COURSES_ADVANCED_BACKEND          8
NUM_COURSES_ADVANCED_DATASCIENCE      2
Unnamed: 0                            0
NAME                                  0
USER_ID                               0
PROFILE                               0
dtype: int64

In [4]:
print('Shape of the dataframe: '+str(data.shape))

Shape of the dataframe: (20000, 16)

In [5]:
print('Class balance in the dataset: '+str(data['PROFILE'].value_counts()))

Class balance in the dataset: advanced_backend         3339
advanced_front_end       3337
beginner_front_end       3335
beginner_backend         3332
advanced_data_science    3330
beginner_data_science    3327
Name: PROFILE, dtype: int64

Because there are 20000 students in this dataset, we can easily discard the rows with missing values. We only need to check if the class balance is still quite okay. So what if we discard these rows?

In [6]:
data = data.dropna()
data

,Unnamed: 0,NAME,USER_ID,HOURS_DATASCIENCE,HOURS_BACKEND,HOURS_FRONTEND,NUM_COURSES_BEGINNER_DATASCIENCE,NUM_COURSES_BEGINNER_BACKEND,NUM_COURSES_BEGINNER_FRONTEND,NUM_COURSES_ADVANCED_DATASCIENCE,NUM_COURSES_ADVANCED_BACKEND,NUM_COURSES_ADVANCED_FRONTEND,AVG_SCORE_DATASCIENCE,AVG_SCORE_BACKEND,AVG_SCORE_FRONTEND,PROFILE
11,511,Marc Ferris,34028847,39.0,52.0,34.0,2.0,4.0,4.0,1.0,5.0,5.0,69.0,65.0,73.0,beginner_backend
12,512,Monique Vaughn,87147288,28.0,44.0,16.0,3.0,2.0,5.0,0.0,4.0,4.0,41.0,40.0,76.0,beginner_data_science
13,513,Laurie Ropers,28065441,74.0,36.0,41.0,2.0,5.0,2.0,3.0,4.0,2.0,52.0,77.0,66.0,advanced_front_end
14,514,Roberto Russell,13095342,69.0,40.0,18.0,4.0,3.0,5.0,4.0,7.0,6.0,40.0,82.0,78.0,advanced_data_science
15,515,Laura Tofil,81228144,46.0,102.0,44.0,7.0,9.0,3.0,5.0,3.0,3.0,69.0,94.0,50.0,advanced_front_end
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,20495,Rose Jurado,66754730,0.0,44.0,42.0,8.0,4.0,7.0,3.0,3.0,3.0,74.0,73.0,93.0,advanced_backend
19996,20496,Johnny Jones,6874888,0.0,85.0,63.0,3.0,5.0,0.0,4.0,7.0,3.0,50.0,83.0,94.0,advanced_front_end
19997,20497,Lawrence Givens,83752787,32.0,50.0,22.0,0.0,4.0,0.0,6.0,2.0,3.0,61.0,81.0,75.0,advanced_backend
19998,20498,Betty Diclaudio,45806698,0.0,96.0,69.0,3.0,3.0,3.0,5.0,7.0,4.0,64.0,68.0,68.0,advanced_front_end
19999,20499,Connie Harper,67068866,51.0,24.0,36.0,4.0,2.0,7.0,0.0,0.0,2.0,63.0,61.0,87.0,advanced_data_science

In [7]:
print('Class balance in the dataset: '+str(data['PROFILE'].value_counts()))

Class balance in the dataset: advanced_backend         3263
advanced_data_science    3250
advanced_front_end       3244
beginner_data_science    3215
beginner_front_end       3209
beginner_backend         3147
Name: PROFILE, dtype: int64

The class balance is still okay and the amount of rows are still large so that this will not effect the models of classifying.

Now are the columns 'Unnamed: 0', 'NAME' and 'USER_ID' not columns we can use for classification because this will not correlate with the class label. We can drop these columns

In [8]:
data = data.drop(['Unnamed: 0', 'NAME', 'USER_ID'], axis = 1)
data

,HOURS_DATASCIENCE,HOURS_BACKEND,HOURS_FRONTEND,NUM_COURSES_BEGINNER_DATASCIENCE,NUM_COURSES_BEGINNER_BACKEND,NUM_COURSES_BEGINNER_FRONTEND,NUM_COURSES_ADVANCED_DATASCIENCE,NUM_COURSES_ADVANCED_BACKEND,NUM_COURSES_ADVANCED_FRONTEND,AVG_SCORE_DATASCIENCE,AVG_SCORE_BACKEND,AVG_SCORE_FRONTEND,PROFILE
11,39.0,52.0,34.0,2.0,4.0,4.0,1.0,5.0,5.0,69.0,65.0,73.0,beginner_backend
12,28.0,44.0,16.0,3.0,2.0,5.0,0.0,4.0,4.0,41.0,40.0,76.0,beginner_data_science
13,74.0,36.0,41.0,2.0,5.0,2.0,3.0,4.0,2.0,52.0,77.0,66.0,advanced_front_end
14,69.0,40.0,18.0,4.0,3.0,5.0,4.0,7.0,6.0,40.0,82.0,78.0,advanced_data_science
15,46.0,102.0,44.0,7.0,9.0,3.0,5.0,3.0,3.0,69.0,94.0,50.0,advanced_front_end
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.0,44.0,42.0,8.0,4.0,7.0,3.0,3.0,3.0,74.0,73.0,93.0,advanced_backend
19996,0.0,85.0,63.0,3.0,5.0,0.0,4.0,7.0,3.0,50.0,83.0,94.0,advanced_front_end
19997,32.0,50.0,22.0,0.0,4.0,0.0,6.0,2.0,3.0,61.0,81.0,75.0,advanced_backend
19998,0.0,96.0,69.0,3.0,3.0,3.0,5.0,7.0,4.0,64.0,68.0,68.0,advanced_front_end
19999,51.0,24.0,36.0,4.0,2.0,7.0,0.0,0.0,2.0,63.0,61.0,87.0,advanced_data_science

Now every column, except for the label is a number. The dataset is ready for implementation in models. This dataset contains only 12 features so this is not that much so we don't apply dimensionality reduction to it.

Now we need to write this resulting dataset to a csv file.

In [9]:
data.to_csv('dataset_1.csv', index = False)